### ISSUE TITLE
flask_compress ModuleNotFoundError while attempting to run captum insights example

### ISSUE THREAD

**Issue by smurching** [meta-pytorch/captum#673]
## 🐛 Bug

I tried to run the captum insights example documented in the README after installing captum via conda-forge:
```
python -m captum.insights.example  
```

However, I got the following error:
```
Traceback (most recent call last):
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in start
    self.subapp.start()
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 708, in start
    self.install_extensions()
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 687, in install_extensions
    **kwargs
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/captum/insights/__init__.py", line 1, in <module>
    from captum.insights.attr_vis import AttributionVisualizer, Batch  # noqa
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/captum/insights/attr_vis/__init__.py", line 1, in <module>
    from captum.insights.attr_vis.app import AttributionVisualizer, Batch  # noqa
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/captum/insights/attr_vis/app.py", line 30, in <module>
    from captum.insights.attr_vis.server import namedtuple_to_dict
  File "/Users/sid.murching/opt/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/captum/insights/attr_vis/server.py", line 10, in <module>
    from flask_compress import Compress
ModuleNotFoundError: No module named 'flask_compress'
```

## To Reproduce

1. Created a Python 3.6 conda environment (in this case named "mlflow-dev-env") via `conda create -q -n mlflow-dev-env python=3.6`
2. Installed captum via `conda install captum -c pytorch`
3. Ran `python -m captum.insights.example`

## Environment
Describe the environment used for Captum

 - Captum / PyTorch Version (e.g., 1.0 / 0.4.0): captum=0.3.1=0,  pytorch=1.7.1=py3.6_0
 - OS (e.g., Linux): Mac OSX
 - How you installed Captum / PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): n/a
 - Python version: 3.6.10
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: See full conda env below

## Additional context

Here's the contents of my current conda environment:

```
(mlflow-dev-env) ➜  ~  conda env export -n mlflow-dev-env 
name: mlflow-dev-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=3.1.0=py36h79c6626_0
  - appnope=0.1.2=py36h79c6626_1
  - argon2-cffi=20.1.0=py36h20b66c6_2
  - async_generator=1.10=py_0
  - babel=2.9.1=pyh44b312d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py36h20b66c6_1001
  - ca-certificates=2020.12.5=h033912b_0
  - captum=0.3.1=0
  - certifi=2020.12.5=py36h79c6626_1
  - cffi=1.14.5=py36hfaecaff_0
  - chardet=4.0.0=py36h79c6626_1
  - contextvars=2.4=py_0
  - cryptography=3.4.7=py36h3d45be8_0
  - dataclasses=0.8=pyh4f3eec9_6
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=ha233b18_0
  - idna=2.10=pyh9f0ad1d_0
  - immutables=0.15=py36h49ba835_0
  - importlib-metadata=4.0.1=py36h79c6626_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - ipykernel=5.5.5=py36h495a4c6_0
  - ipython_genutils=0.2.0=py_1
  - jpeg=9b=he5867d9_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py36h79c6626_0
  - jupyter_server=1.8.0=pyhd8ed1ab_0
  - jupyterlab=3.0.16=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.5.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py36h23ab428_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.1.0=hcb84e12_1
  - libuv=1.40.0=haf1e3a3_0
  - lz4-c=1.9.3=h23ab428_0
  - matplotlib=3.3.4=py36hecd8cb5_0
  - matplotlib-base=3.3.4=py36h8b3ea08_0
  - mistune=0.8.4=py36h20b66c6_1003
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36h9ed2024_0
  - mkl_fft=1.3.0=py36ha059aab_0
  - mkl_random=1.0.4=py36h27c97d8_0
  - nbclassic=0.3.1=pyhd8ed1ab_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36h79c6626_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=hf7b0b51_1
  - notebook=6.3.0=py36h79c6626_0
  - numpy-base=1.17.0=py36h6575580_0
  - olefile=0.46=py36_0
  - openssl=1.1.1k=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.13=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py36h5270095_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py36h20b66c6_2
  - pysocks=1.7.1=py36h79c6626_3
  - python=3.6.13=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.7.1=py3.6_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=20.0.0=py36h23ab428_1
  - readline=8.1=h9ed2024_0
  - requests=2.25.1=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py36hecd8cb5_0
  - simplegeneric=0.8.1=py_1
  - six=1.15.0=py36hecd8cb5_0
  - sniffio=1.2.0=py36h79c6626_1
  - sqlite=3.35.4=hce871da_0
  - terminado=0.10.0=py36h79c6626_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py36h9ed2024_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - absl-py==0.12.0
    - adal==1.2.7
    - aiohttp==3.7.4.post0
    - alembic==1.4.1
    - applicationinsights==0.11.10
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==20.3.0
    - aws-sam-translator==1.35.0
    - aws-xray-sdk==2.8.0
    - azure-common==1.1.27
    - azure-core==1.13.0
    - azure-graphrbac==0.61.1
    - azure-identity==1.5.0
    - azure-mgmt-authorization==1.0.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-core==1.2.2
    - azure-mgmt-keyvault==9.0.0
    - azure-mgmt-resource==8.0.1
    - azure-mgmt-storage==17.1.0
    - azure-storage-blob==12.8.1
    - azureml-automl-core==1.2.0
    - azureml-core==1.2.0.post3
    - azureml-dataprep==1.3.6
    - azureml-dataprep-native==14.2.1
    - azureml-pipeline==1.2.0
    - azureml-pipeline-core==1.2.0
    - azureml-pipeline-steps==1.2.0
    - azureml-sdk==1.2.0
    - azureml-telemetry==1.2.0
    - azureml-train==1.2.0
    - azureml-train-automl-client==1.2.0
    - azureml-train-core==1.2.0
    - azureml-train-restclients-hyperdrive==1.2.0
    - backcall==0.2.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - beautifulsoup4==4.9.3
    - blis==0.7.4
    - boto==2.49.0
    - boto3==1.17.67
    - botocore==1.20.67
    - bottleneck==1.3.2
    - cachetools==4.2.2
    - catalogue==2.0.4
    - catboost==0.25.1
    - cfn-lint==0.49.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - contextlib2==0.6.0.post1
    - coverage==5.5
    - cycler==0.10.0
    - cymem==2.0.5
    - databricks-cli==0.14.3
    - decorator==4.4.2
    - distro==1.5.0
    - docker==5.0.0
    - dotnetcore2==2.1.20
    - ecdsa==0.14.1
    - fastai==1.0.60
    - fastprogress==1.0.0
    - flake8==3.7.9
    - flask==1.1.2
    - flatbuffers==1.12
    - fsspec==2021.4.0
    - fusepy==3.0.1
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - greenlet==1.0.0
    - grpcio==1.32.0
    - gunicorn==20.1.0
    - h2o==3.32.1.2
    - h5py==2.10.0
    - idna-ssl==1.1.0
    - importlib-resources==3.3.1
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jedi==0.18.0
    - jeepney==0.6.0
    - jinja2==2.11.3
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsondiff==1.3.0
    - jsonpatch==1.32
    - jsonpickle==2.0.0
    - jsonpointer==2.1
    - junit-xml==1.9
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - lightgbm==3.2.1
    - llvmlite==0.36.0
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - mleap==0.16.1
    - mock==4.0.3
    - more-itertools==8.7.0
    - moto==1.3.16
    - msal==1.11.0
    - msal-extensions==0.3.0
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multidict==5.1.0
    - murmurhash==1.0.5
    - mxnet==1.7.0.post2
    - ndg-httpsclient==0.5.1
    - networkx==2.5.1
    - numba==0.53.1
    - numexpr==2.7.3
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - onnx==1.9.0
    - onnxruntime==1.7.0
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - parso==0.8.2
    - pathspec==0.8.1
    - pathy==0.5.2
    - patsy==0.5.1
    - pip==21.1.1
    - plotly==4.14.3
    - portalocker==1.7.1
    - preshed==3.0.5
    - prometheus-flask-exporter==0.18.2
    - prompt-toolkit==3.0.18
    - protobuf==3.15.8
    - py==1.10.0
    - py4j==0.10.9
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pydantic==1.7.3
    - pyflakes==2.1.1
    - pyjwt==2.1.0
    - pynvx==1.0.0
    - pyspark==3.1.1
    - pytest==3.2.1
    - pytest-cov==2.6.0
    - pytest-localserver==0.5.0
    - python-editor==1.0.4
    - python-graphviz==0.8.4
    - python-jose==3.2.0
    - pytorch-lightning==1.2.10
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - requests-oauthlib==1.3.0
    - responses==0.13.3
    - retrying==1.3.3
    - rsa==4.7.2
    - ruamel-yaml==0.15.89
    - s3transfer==0.4.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - secretstorage==3.3.1
    - shap==0.39.0
    - slicer==0.0.7
    - smart-open==3.0.0
    - smmap==4.0.0
    - soupsieve==2.2.1
    - spacy==3.0.6
    - spacy-legacy==3.0.5
    - sqlalchemy==1.4.13
    - sqlparse==0.4.1
    - srsly==2.4.1
    - sshpubkeys==3.3.1
    - statsmodels==0.12.2
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - tf2onnx==1.8.4
    - thinc==8.0.3
    - threadpoolctl==2.1.0
    - torch==1.8.1
    - torchmetrics==0.2.0
    - torchvision==0.9.1
    - tqdm==4.60.0
    - typer==0.3.2
    - wasabi==0.8.2
    - websocket-client==0.59.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xgboost==1.4.1
    - xmltodict==0.12.0
    - yarl==1.6.3
```

**Comment by smurching** [comment]
Explicitly installing flask-compress via ``pip install Flask-Compress `` fixed the issue for me

**Comment by NarineK** [comment]
@bilalsal , @Reubend , do you mind adding that description in the installation section of insights ?

**Comment by Reubend** [comment]
Hi there @smurching may I ask if you followed the commands in the Insights section of the readme? I can see from your steps to reproduce that you're running conda install directly, but `readme.md` points out that some additional steps are necessary to run Insights:
```
conda install -c conda-forge yarn
BUILD_INSIGHTS=1 python setup.py develop
python captum/insights/example.py
```

Maybe we can make the readme easier to understand about this point... the directions are almost hidden because the install steps are underneath the "basic" install steps (which don't include everything you need for Insights). 

I also see a possible issue with `setup.py`... it seems to me like running with the `BUILD_INSIGHTS` flag doesn't activate the "extra" dependencies for Insights which get declared, in the way that running `pip install -e .[insights]` would. @NarineK is my understanding here wrong? If this is happening, I can fix it by making the flag activate those extra dependencies too (and make the readme a bit easier to understand too).

**Comment by NarineK** [comment]
Thank you for checking it @Reubend ! I think that we already added extra install in the setup. I think that this should suffice if we install insights dependancies.
https://github.com/pytorch/captum/blob/master/setup.py#L54

@smurching, let us know if you tried the instructions for the install of insights component.

**Comment by craymichael** [comment]
Closing due to inactivity.
